name: Release Desktop App

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
            target: "aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
            target: "x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
            target: "x86_64-unknown-linux-gnu"
          - platform: "windows-latest"
            args: ""
            target: "x86_64-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src-tauri -> target"
          cache-targets: "false"

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm install

      - name: Generate app icon
        run: |
          cd src-tauri
          npx @tauri-apps/cli icon icons/icon.svg

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "OCPP CP Simulator ${{ github.ref_name }}"
          releaseBody: |
            See the assets to download this version and install.

            ## What's Changed

            ### Desktop App Downloads
            - **macOS (Apple Silicon)**: `OCPP.CP.Simulator_*_aarch64.dmg`
            - **macOS (Intel)**: `OCPP.CP.Simulator_*_x64.dmg`
            - **Windows**: `OCPP.CP.Simulator_*_x64-setup.exe` or `.msi`
            - **Linux**: `ocpp-cp-simulator_*_amd64.AppImage` or `.deb`

            ### Web Version
            The web version is available at: https://shiv3.github.io/ocpp-cp-simulator/
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

  update-release-notes:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate release notes
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.ref.replace('refs/tags/', '')
            });

            // Get commit history
            let body = release.body;

            try {
              const { data: commits } = await github.rest.repos.compareCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                base: 'v0.0.0', // Previous tag - update this
                head: context.ref.replace('refs/tags/', '')
              });
              
              const commitList = commits.commits
                .map(c => `- ${c.commit.message.split('\n')[0]} (${c.sha.substring(0, 7)})`)
                .join('\n');
              
              body = body.replace('## What\'s Changed', `## What's Changed\n\n### Commits\n${commitList}\n`);
            } catch (e) {
              console.log('Failed to get commit history:', e.message);
            }

            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
              body: body
            });
